[package]
name = "simple_library"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "example_wasm"
path = "src-rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
lingua_luau = { path = "../../rust" }
serde = { version = "1.0.203", features = ["derive"] }
